exp: '075'
run_mode: 'full'
task_type: 'grid_pred'

mul_old_factor: true
use_grid_feat: false
shared_valid: false
valid_ratio: 0.20
input_shape: '3dim'
input_scale_method: 'standard'
multi_task: false

model_type: 'conv1d'
in_dim: 30
out_dim: 384
hidden_dim: 256
block_num: 5
kernel_size: 5

loss_type: 'mae'
ema: false
ema_decay: 0.999
train_batch: 1024
eval_batch: 4096
epochs: 10
eval_step:
  full: 4000
  dev: 2000
  debug: 20

optimizer_type: 'adamw'
lr: 5e-4
weight_decay: 0.01
betas:
  - 0.9
  - 0.999

scheduler_type: 'cosine_custom'
first_cycle_epochs: 15
num_warmup_steps: 200
cycle_factor: 1
min_lr: 5e-6
gamma: 1.0
