exp: '147'
run_mode: 'hf'
task_type: 'main'

mul_old_factor: true
use_grid_feat: false
shared_valid: true
valid_ratio: 0.20
input_shape: '3dim'
target_shape: '3dim'
input_scale_method: 'standard'
target_scale_method: 'standard_y2'
multi_task: false

model_type: 'transformer'
in_dim: 86
out_dim: 14
hidden_dim: 256
scaler_num: 16
trans_num_layers: 4
lstm_block_num: 2

loss_type: 'mae'
ema: false
ema_decay: 0.999
train_batch: 1024
eval_batch: 4096
batch_file_size: 5 # total=89
epochs: 240
eval_step:
  hf: 4000
  full: 4000
  dev: 2000
  debug: 20
out_clip: true

optimizer_type: 'adamw'
lr: 5e-4
weight_decay: 0.01
betas:
  - 0.9
  - 0.999

scheduler_type: 'cosine_custom'
first_cycle_epochs: 240
num_warmup_steps: 200
cycle_factor: 1
min_lr: 5e-6
gamma: 1.0

add_loss_type: 'mse'
add_epochs: 90
add_lr: 1e-5
add_first_cycle_epochs: 90
