exp: '149'
run_mode: 'hf'  # hf, full, dev, debug
task_type: 'main'

mul_old_factor: true
use_grid_feat: false
shared_valid: true
valid_ratio: 0.20
input_shape: '3dim'
target_shape: '3dim'
input_scale_method: 'standard'
target_scale_method: 'standard_y2'
multi_task: false

model_type: 'lstm'
in_dim: 86
out_dim: 14
hidden_dim: 256
scaler_num: 16
block_num: 6

loss_type: 'mse'
ema: false
train_batch: 1024
eval_batch: 4096
batch_file_size: 10
epochs: 100
eval_step:
  hf: 4000
  full: 4000
  dev: 2000
  debug: 20
out_clip: true

optimizer_type: 'adamw'
lr: 5e-4
weight_decay: 0.01
betas:
  - 0.9
  - 0.999

scheduler_type: 'cosine_custom'
first_cycle_epochs: 100
num_warmup_steps: 200
cycle_factor: 1
min_lr: 5e-6
gamma: 1.0

